export const products = [
  {
    id: 10,
    name: "",
    price: 11990,
    image: "/img-products/ola.jpg",
    category: "Polera",
    con_tallas: 1,
    tallas: [35, 36, 37, 38, 39],
    oferta: 1,
    precio_oferta: 490,
  },
  
  {
    id: 9,
    name: "Producto 2",
    price: 500,
    image: "/img-products/1.jpg",
    category: "Zapato",
    con_tallas: 1,
    tallas: [35, 36, 37, 38, 39],
    oferta: 1,
    precio_oferta: 190,
  },
  {
    id: 8,
    name: "Producto 2",
    price: 233,
    image: "/img-products/2.jpg",
    category: "Zapato",
    con_tallas: 0,
    oferta: 0,
    precio_oferta: 0,
  },
  {
    id: 7,
    name: "Producto 2",
    price: 12000,
    image: "/img-products/2.jpg",
    category: "Zapato",
    con_tallas: 0,
    oferta: 0,
    precio_oferta: 0,
  },
];
